[package]
name = "strata"
version = "0.1.0"
authors = ["fabianboesiger <boesiger.fabian@outlook.com>"]
edition = "2018"

[dependencies]
image = "0.23"
rayon = "1.3"
nalgebra = "0.20"
partitions = "0.2"
iced = "0.1"